
format = """
$directory\
[](fg:color_blue bg:color_blue2)\
$git_branch\
$git_status\
[](color_blue2)\
$fill\
[](color_blue2)\
$time\
\n$character
"""

# Inserts a blank line between shell prompts
add_newline = true

palette = 'tokyonight'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[fill]
symbol = ' '

[palettes.tokyonight]
color_black = '#15161e'
color_red = '#f7768e'
color_green = '#9ece6a'
color_yellow = '#e0af68'
color_blue = '#7aa2f7'
color_blue2 = '#3b4261'
color_magenta = '#bb9af7'
color_cyan = '#7dcfff'
color_white = '#a9b1d6'
color_dark = '#1f2335'


[directory]
style = "fg:color_black bg:color_blue"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:color_blue2"
format = '[[ $symbol $branch ](fg:color_blue bg:color_blue2)]($style)'

[git_status]
style = "bg:color_blue2"
format = '[[($all_status$ahead_behind )](fg:color_blue bg:color_blue2)]($style)'


[time]
disabled = false
time_format = "%T" # Hour:Minute Format
style = "bg:color_blue2"
format = '[[ $time ](fg:color_blue bg:color_blue2)]($style)'

