
format = """
$directory\
${custom.git_status_no_repo}\
${custom.git_status_clean}\
${custom.git_status_dirty}\
$fill\
[](color_blue2)\
$time\
\n$character
"""

# Inserts a blank line between shell prompts
add_newline = true

palette = 'tokyonight'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[fill]
symbol = ' '

[palettes.tokyonight]
color_black = '#15161e'
color_red = '#f7768e'
color_green = '#9ece6a'
color_yellow = '#e0af68'
color_blue = '#7aa2f7'
color_blue2 = '#3b4261'
color_magenta = '#bb9af7'
color_cyan = '#7dcfff'
color_white = '#a9b1d6'
color_dark = '#1f2335'


[directory]
style = "fg:color_black bg:color_blue"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[custom.git_status_no_repo]
when = 'test -z "$(git rev-parse --is-inside-work-tree)"'
format = '[](color_blue)'

[custom.git_status_clean]
require_repo = true
when = 'test -z "$(git status --porcelain)"'
command = '''
git_branch=$(git branch --show-current)
if [ -z $git_branch ]; then
  echo -n ""
else
  echo -n " $git_branch"
fi
'''
style = "bg:color_blue2"
format = '[](fg:color_blue bg:color_blue2)[ $output ](fg:color_blue bg:color_blue2)[](color_blue2)'

[custom.git_status_dirty]
require_repo = true
when = 'test -n "$(git status --porcelain)"'
command = '''
git_branch=$(git branch --show-current)
if [ -z $git_branch ]; then
  echo -n ""
else
  echo -n "  $git_branch"
fi
'''
style = "bg:color_yellow"
format = '[](fg:color_blue bg:color_yellow)[ $output ](fg:color_black bg:color_yellow)[](color_yellow)'

[time]
disabled = false
time_format = "%T"
style = "bg:color_blue2"
format = '[[ $time ](fg:color_blue bg:color_blue2)]($style)'

