[terminal.shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux new-session -A -D -s default"]


[env]
TERM="screen-256color"


# TokyoNight Alacritty Colors
# Default colors
[colors.primary]
background = '#1a1b26'
foreground = '#c0caf5'

[colors.cursor]
cursor = '#c0caf5'
#text = '#1a1b26'

# Normal colors
[colors.normal]
black = '#15161e'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#a9b1d6'

# Bright colors
[colors.bright]
black = '#414868'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#c0caf5'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#ff9e64'

[[colors.indexed_colors]]
index = 17
color = '#db4b4b'

[window]
# option_as_alt = "Both"
startup_mode = "Maximized"
decorations = "Transparent"
padding = { x = 8, y = 24 }
dynamic_padding = true
# opacity = 0.9

[keyboard]
bindings = [
     { key = "J", mods = "Alt", chars = "\u001bj" },
     { key = "K", mods = "Alt", chars = "\u001bk" },
     { key = "H", mods = "Alt", chars = "\u001bh" },
     { key = "L", mods = "Alt", chars = "\u001bl" },
]


[font]
normal = { family = "MonaspiceAr Nerd Font", style = "Light" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = {  style = "BoldItalic" }
size = 16.0

[terminal]

