column_width = 120
line_endings = "Unix"
indent_type = "Space"
indent_width = 3
quote_style = "AutoPreferDouble"
call_parentheses = "Always"
collapse_simple_statement = "Always"

[sort_requires]
enabled = false
